///////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2026 Jean-Philippe Steinmetz. All rights reserved.
// SPDX-License-Identifier: MPL-2.0
///////////////////////////////////////////////////////////////////////////////

/**
 * WBXML code page index -> namespace name, per MS-ASWBXML §2.1.2.1 ("List of Code Pages"). A code page is
 * WBXML's mechanism for reusing the single-byte tag-token space across many XML namespaces: a `SWITCH_PAGE`
 * global token changes which of these tables subsequent tag bytes are looked up against.
 *
 * @author Jean-Philippe Steinmetz
 */
export enum WbxmlCodePage {
    AirSync = 0,
    Contacts = 1,
    Email = 2,
    AirNotification = 3,
    Calendar = 4,
    Move = 5,
    ItemEstimate = 6,
    FolderHierarchy = 7,
    MeetingResponse = 8,
    Tasks = 9,
    ResolveRecipients = 10,
    ValidateCert = 11,
    Contacts2 = 12,
    Ping = 13,
    Provision = 14,
    Search = 15,
    Gal = 16,
    AirSyncBase = 17,
    Settings = 18,
    DocumentLibrary = 19,
    ItemOperations = 20,
    ComposeMail = 21,
    Email2 = 22,
    Notes = 23,
    RightsManagement = 24,
    Find = 25,
}

/**
 * Tag name -> token (byte, before the content/attribute flag bits are applied) tables, one per code page
 * actually touched by this library's pragmatic command subset (`Provision`/`FolderSync`/`Sync`/`SendMail`/
 * `SmartForward`/`SmartReply`/`ItemOperations`/`Ping`/`Search`/`MeetingResponse`/`Settings`). Deferred pages
 * (`AirNotification`, `Move`, `ItemEstimate`, `ResolveRecipients`, `ValidateCert`, `DocumentLibrary`, `Notes`,
 * `RightsManagement`, `Find`) are registered in `WbxmlCodePage` above (so `SWITCH_PAGE` decoding never fails
 * outright on them) but have no tag table here — nothing in this library's supported command set ever needs
 * to encode/decode a tag from one of them.
 *
 * Values for `AirSync` (0) and `FolderHierarchy` (7) are transcribed directly from the published
 * [MS-ASWBXML] tables (`Code Page 0: AirSync`, `Code Page 7: FolderHierarchy`, learn.microsoft.com). Every
 * other page's values come from Z-Push's `wbxmldefs.php` (github.com/Z-Hub/Z-Push,
 * `src/lib/wbxml/wbxmldefs.php`) — a production, real-device-tested open-source ActiveSync server whose
 * numeric token tables are necessarily byte-exact against the wire protocol (a handful of its internal PHP
 * array-key names were normalized here to the tag names used elsewhere in the public spec/blog examples,
 * e.g. `Synchronize`->`Sync`, `Replies`->`Responses`, `Modify`->`Change`, `Remove`->`Delete` on page 0; the
 * numeric token values themselves were not changed). A handful of legacy/deprecated token slots absent from
 * the *current* published MS-ASWBXML tables but still present in Z-Push (e.g. AirSync `0x11 Version`, `0x1A
 * RtfTruncation`, `0x1F NotifyGUID`) are kept so this codec can still decode older real-world traffic that
 * may use them; they are marked `deprecated` in the table below and are never emitted by this library's own
 * encoder.
 */
const TAGS_BY_PAGE: Readonly<Record<number, Readonly<Record<number, string>>>> = {
    [WbxmlCodePage.AirSync]: {
        0x05: "Sync",
        0x06: "Responses",
        0x07: "Add",
        0x08: "Change",
        0x09: "Delete",
        0x0a: "Fetch",
        0x0b: "SyncKey",
        0x0c: "ClientId",
        0x0d: "ServerId",
        0x0e: "Status",
        0x0f: "Collection",
        0x10: "Class",
        0x11: "Version", // deprecated
        0x12: "CollectionId",
        0x13: "GetChanges",
        0x14: "MoreAvailable",
        0x15: "WindowSize",
        0x16: "Commands",
        0x17: "Options",
        0x18: "FilterType",
        0x19: "Truncation", // 2.5 only
        0x1a: "RtfTruncation", // deprecated
        0x1b: "Conflict",
        0x1c: "Collections",
        0x1d: "ApplicationData",
        0x1e: "DeletesAsMoves",
        0x1f: "NotifyGUID", // deprecated
        0x20: "Supported",
        0x21: "SoftDelete",
        0x22: "MIMESupport",
        0x23: "MIMETruncation",
        0x24: "Wait",
        0x25: "Limit",
        0x26: "Partial",
        0x27: "ConversationMode",
        0x28: "MaxItems",
        0x29: "HeartbeatInterval",
    },
    [WbxmlCodePage.Contacts]: {
        0x05: "Anniversary",
        0x06: "AssistantName",
        0x07: "AssistantTelephoneNumber",
        0x08: "Birthday",
        0x09: "Body", // legacy (2.5); AirSyncBase Body used since 12.0
        0x0a: "BodySize",
        0x0b: "BodyTruncated",
        0x0c: "Business2PhoneNumber",
        0x0d: "BusinessCity",
        0x0e: "BusinessCountry",
        0x0f: "BusinessPostalCode",
        0x10: "BusinessState",
        0x11: "BusinessStreet",
        0x12: "BusinessFaxNumber",
        0x13: "BusinessPhoneNumber",
        0x14: "CarPhoneNumber",
        0x15: "Categories",
        0x16: "Category",
        0x17: "Children",
        0x18: "Child",
        0x19: "CompanyName",
        0x1a: "Department",
        0x1b: "Email1Address",
        0x1c: "Email2Address",
        0x1d: "Email3Address",
        0x1e: "FileAs",
        0x1f: "FirstName",
        0x20: "Home2PhoneNumber",
        0x21: "HomeCity",
        0x22: "HomeCountry",
        0x23: "HomePostalCode",
        0x24: "HomeState",
        0x25: "HomeStreet",
        0x26: "HomeFaxNumber",
        0x27: "HomePhoneNumber",
        0x28: "JobTitle",
        0x29: "LastName",
        0x2a: "MiddleName",
        0x2b: "MobilePhoneNumber",
        0x2c: "OfficeLocation",
        0x2d: "OtherCity",
        0x2e: "OtherCountry",
        0x2f: "OtherPostalCode",
        0x30: "OtherState",
        0x31: "OtherStreet",
        0x32: "PagerNumber",
        0x33: "RadioPhoneNumber",
        0x34: "Spouse",
        0x35: "Suffix",
        0x36: "Title",
        0x37: "WebPage",
        0x38: "YomiCompanyName",
        0x39: "YomiFirstName",
        0x3a: "YomiLastName",
        0x3b: "CompressedRTF", // deprecated
        0x3c: "Picture",
        0x3d: "Alias",
        0x3e: "WeightedRank",
    },
    [WbxmlCodePage.Email]: {
        0x05: "Attachment", // legacy; AirSyncBase Attachments used since 12.0
        0x06: "Attachments",
        0x07: "AttName",
        0x08: "AttSize",
        0x09: "AttOid",
        0x0a: "AttMethod",
        0x0b: "AttRemoved",
        0x0c: "Body",
        0x0d: "BodySize",
        0x0e: "BodyTruncated",
        0x0f: "DateReceived",
        0x10: "DisplayTo",
        0x11: "DisplayCc",
        0x12: "Importance",
        0x13: "MessageClass",
        0x14: "Subject",
        0x15: "Read",
        0x16: "To",
        0x17: "Cc",
        0x18: "From",
        0x19: "ReplyTo",
        0x1a: "AllDayEvent",
        0x1b: "Categories",
        0x1c: "Category",
        0x1d: "DtStamp",
        0x1e: "EndTime",
        0x1f: "InstanceType",
        0x20: "BusyStatus",
        0x21: "Location",
        0x22: "MeetingRequest",
        0x23: "Organizer",
        0x24: "RecurrenceId",
        0x25: "Reminder",
        0x26: "ResponseRequested",
        0x27: "Recurrences",
        0x28: "Recurrence",
        0x29: "Type",
        0x2a: "Until",
        0x2b: "Occurrences",
        0x2c: "Interval",
        0x2d: "DayOfWeek",
        0x2e: "DayOfMonth",
        0x2f: "WeekOfMonth",
        0x30: "MonthOfYear",
        0x31: "StartTime",
        0x32: "Sensitivity",
        0x33: "TimeZone",
        0x34: "GlobalObjId",
        0x35: "ThreadTopic",
        0x36: "MIMEData", // 2.5, deprecated
        0x37: "MIMETruncated",
        0x38: "MIMESize",
        0x39: "InternetCPID",
        0x3a: "Flag",
        0x3b: "FlagStatus",
        0x3c: "ContentClass",
        0x3d: "FlagType",
        0x3e: "CompleteTime",
        0x3f: "DisallowNewTimeProposal",
    },
    [WbxmlCodePage.Calendar]: {
        0x05: "Timezone",
        0x06: "AllDayEvent",
        0x07: "Attendees",
        0x08: "Attendee",
        0x09: "Email",
        0x0a: "Name",
        0x0b: "Body",
        0x0c: "BodyTruncated",
        0x0d: "BusyStatus",
        0x0e: "Categories",
        0x0f: "Category",
        0x10: "CompressedRTF", // deprecated
        0x11: "DtStamp",
        0x12: "EndTime",
        0x13: "Exception",
        0x14: "Exceptions",
        0x15: "Deleted",
        0x16: "ExceptionStartTime",
        0x17: "Location",
        0x18: "MeetingStatus",
        0x19: "OrganizerEmail",
        0x1a: "OrganizerName",
        0x1b: "Recurrence",
        0x1c: "Type",
        0x1d: "Until",
        0x1e: "Occurrences",
        0x1f: "Interval",
        0x20: "DayOfWeek",
        0x21: "DayOfMonth",
        0x22: "WeekOfMonth",
        0x23: "MonthOfYear",
        0x24: "Reminder",
        0x25: "Sensitivity",
        0x26: "Subject",
        0x27: "StartTime",
        0x28: "UID",
        0x29: "AttendeeStatus",
        0x2a: "AttendeeType",
        0x2b: "Attachment", // deprecated
        0x2c: "Attachments", // deprecated
        0x2d: "AttName", // deprecated
        0x2e: "AttSize", // deprecated
        0x2f: "AttOid", // deprecated
        0x30: "AttMethod", // deprecated
        0x31: "AttRemoved", // deprecated
        0x32: "DisplayName", // deprecated
        0x33: "DisallowNewTimeProposal",
        0x34: "ResponseRequested",
        0x35: "AppointmentReplyTime",
        0x36: "ResponseType",
        0x37: "CalendarType",
        0x38: "IsLeapMonth",
        0x39: "FirstDayOfWeek",
        0x3a: "OnlineMeetingConfLink",
        0x3b: "OnlineMeetingExternalLink",
        0x3c: "ClientUid",
    },
    [WbxmlCodePage.FolderHierarchy]: {
        0x05: "Folders", // legacy (2.5, 12.0, 12.1)
        0x06: "Folder", // legacy
        0x07: "DisplayName",
        0x08: "ServerId",
        0x09: "ParentId",
        0x0a: "Type",
        0x0b: "Response", // deprecated
        0x0c: "Status",
        0x0d: "ContentClass", // deprecated
        0x0e: "Changes",
        0x0f: "Add",
        0x10: "Delete",
        0x11: "Update",
        0x12: "SyncKey",
        0x13: "FolderCreate",
        0x14: "FolderDelete",
        0x15: "FolderUpdate",
        0x16: "FolderSync",
        0x17: "Count",
        0x18: "Version", // deprecated
    },
    [WbxmlCodePage.MeetingResponse]: {
        0x05: "CalendarId",
        0x06: "CollectionId",
        0x07: "MeetingResponse",
        0x08: "RequestId",
        0x09: "Request",
        0x0a: "Result",
        0x0b: "Status",
        0x0c: "UserResponse",
        0x0d: "Version", // deprecated
        0x0e: "InstanceId",
        0x10: "ProposedStartTime",
        0x11: "ProposedEndTime",
        0x12: "SendResponse",
    },
    [WbxmlCodePage.Tasks]: {
        0x05: "Body",
        0x06: "BodySize",
        0x07: "BodyTruncated",
        0x08: "Categories",
        0x09: "Category",
        0x0a: "Complete",
        0x0b: "DateCompleted",
        0x0c: "DueDate",
        0x0d: "UtcDueDate",
        0x0e: "Importance",
        0x0f: "Recurrence",
        0x10: "Type",
        0x11: "Start",
        0x12: "Until",
        0x13: "Occurrences",
        0x14: "Interval",
        0x15: "DayOfMonth",
        0x16: "DayOfWeek",
        0x17: "WeekOfMonth",
        0x18: "MonthOfYear",
        0x19: "Regenerate",
        0x1a: "DeadOccur",
        0x1b: "ReminderSet",
        0x1c: "ReminderTime",
        0x1d: "Sensitivity",
        0x1e: "StartDate",
        0x1f: "UtcStartDate",
        0x20: "Subject",
        0x21: "CompressedRTF", // deprecated
        0x22: "OrdinalDate",
        0x23: "SubOrdinalDate",
        0x24: "CalendarType",
        0x25: "IsLeapMonth",
        0x26: "FirstDayOfWeek",
    },
    [WbxmlCodePage.Contacts2]: {
        0x05: "CustomerId",
        0x06: "GovernmentId",
        0x07: "IMAddress",
        0x08: "IMAddress2",
        0x09: "IMAddress3",
        0x0a: "ManagerName",
        0x0b: "CompanyMainPhone",
        0x0c: "AccountName",
        0x0d: "NickName",
        0x0e: "MMS",
    },
    [WbxmlCodePage.Ping]: {
        0x05: "Ping",
        0x06: "AutdState", // not used by the protocol
        0x07: "Status",
        0x08: "HeartbeatInterval",
        0x09: "Folders",
        0x0a: "Folder",
        0x0b: "ServerId",
        0x0c: "Class",
        0x0d: "MaxFolders",
        0x0e: "Version", // deprecated
    },
    [WbxmlCodePage.Provision]: {
        0x05: "Provision",
        0x06: "Policies",
        0x07: "Policy",
        0x08: "PolicyType",
        0x09: "PolicyKey",
        0x0a: "Data",
        0x0b: "Status",
        0x0c: "RemoteWipe",
        0x0d: "EASProvisionDoc",
        0x0e: "DevicePasswordEnabled",
        0x0f: "AlphanumericDevicePasswordRequired",
        0x10: "DeviceEncryptionEnabled",
        0x11: "PasswordRecoveryEnabled",
        0x12: "DocumentBrowseEnabled", // deprecated
        0x13: "AttachmentsEnabled",
        0x14: "MinDevicePasswordLength",
        0x15: "MaxInactivityTimeDeviceLock",
        0x16: "MaxDevicePasswordFailedAttempts",
        0x17: "MaxAttachmentSize",
        0x18: "AllowSimpleDevicePassword",
        0x19: "DevicePasswordExpiration",
        0x1a: "DevicePasswordHistory",
        0x1b: "AllowStorageCard",
        0x1c: "AllowCamera",
        0x1d: "RequireDeviceEncryption",
        0x1e: "AllowUnsignedApplications",
        0x1f: "AllowUnsignedInstallationPackages",
        0x20: "MinDevicePasswordComplexCharacters",
        0x21: "AllowWiFi",
        0x22: "AllowTextMessaging",
        0x23: "AllowPOPIMAPEmail",
        0x24: "AllowBluetooth",
        0x25: "AllowIrDA",
        0x26: "RequireManualSyncWhenRoaming",
        0x27: "AllowDesktopSync",
        0x28: "MaxCalendarAgeFilter",
        0x29: "AllowHTMLEmail",
        0x2a: "MaxEmailAgeFilter",
        0x2b: "MaxEmailBodyTruncationSize",
        0x2c: "MaxEmailHTMLBodyTruncationSize",
        0x2d: "RequireSignedSMIMEMessages",
        0x2e: "RequireEncryptedSMIMEMessages",
        0x2f: "RequireSignedSMIMEAlgorithm",
        0x30: "RequireEncryptionSMIMEAlgorithm",
        0x31: "AllowSMIMEEncryptionAlgorithmNegotiation",
        0x32: "AllowSMIMESoftCerts",
        0x33: "AllowBrowser",
        0x34: "AllowConsumerEmail",
        0x35: "AllowRemoteDesktop",
        0x36: "AllowInternetSharing",
        0x37: "UnapprovedInROMApplicationList",
        0x38: "ApplicationName",
        0x39: "ApprovedApplicationList",
        0x3a: "Hash",
        0x3b: "AccountOnlyRemoteWipe",
    },
    [WbxmlCodePage.Search]: {
        0x05: "Search",
        0x07: "Store",
        0x08: "Name",
        0x09: "Query",
        0x0a: "Options",
        0x0b: "Range",
        0x0c: "Status",
        0x0d: "Response",
        0x0e: "Result",
        0x0f: "Properties",
        0x10: "Total",
        0x11: "EqualTo",
        0x12: "Value",
        0x13: "And",
        0x14: "Or",
        0x15: "FreeText",
        0x17: "DeepTraversal",
        0x18: "LongId",
        0x19: "RebuildResults",
        0x1a: "LessThan",
        0x1b: "GreaterThan",
        0x1c: "Schema",
        0x1d: "Supported",
        0x1e: "UserName",
        0x1f: "Password",
        0x20: "ConversationId",
        0x21: "Picture",
        0x22: "MaxSize",
        0x23: "MaxPictures",
    },
    [WbxmlCodePage.Gal]: {
        0x05: "DisplayName",
        0x06: "Phone",
        0x07: "Office",
        0x08: "Title",
        0x09: "Company",
        0x0a: "Alias",
        0x0b: "FirstName",
        0x0c: "LastName",
        0x0d: "HomePhone",
        0x0e: "MobilePhone",
        0x0f: "EmailAddress",
        0x10: "Picture",
        0x11: "Status",
        0x12: "Data",
    },
    [WbxmlCodePage.AirSyncBase]: {
        0x05: "BodyPreference",
        0x06: "Type",
        0x07: "TruncationSize",
        0x08: "AllOrNone",
        0x0a: "Body",
        0x0b: "Data",
        0x0c: "EstimatedDataSize",
        0x0d: "Truncated",
        0x0e: "Attachments",
        0x0f: "Attachment",
        0x10: "DisplayName",
        0x11: "FileReference",
        0x12: "Method",
        0x13: "ContentId",
        0x14: "ContentLocation",
        0x15: "IsInline",
        0x16: "NativeBodyType",
        0x17: "ContentType",
        0x18: "Preview",
        0x19: "BodyPartPreference",
        0x1a: "BodyPart",
        0x1b: "Status",
        0x1c: "Add",
        0x1d: "Delete",
        0x1e: "ClientId",
        0x1f: "Content",
        0x20: "Location",
        0x21: "Annotation",
        0x22: "Street",
        0x23: "City",
        0x24: "State",
        0x25: "Country",
        0x26: "PostalCode",
        0x27: "Latitude",
        0x28: "Longitude",
        0x29: "Accuracy",
        0x2a: "Altitude",
        0x2b: "AltitudeAccuracy",
        0x2c: "LocationUri",
        0x2d: "InstanceId",
    },
    [WbxmlCodePage.Settings]: {
        0x05: "Settings",
        0x06: "Status",
        0x07: "Get",
        0x08: "Set",
        0x09: "Oof",
        0x0a: "OofState",
        0x0b: "StartTime",
        0x0c: "EndTime",
        0x0d: "OofMessage",
        0x0e: "AppliesToInternal",
        0x0f: "AppliesToExternalKnown",
        0x10: "AppliesToExternalUnknown",
        0x11: "Enabled",
        0x12: "ReplyMessage",
        0x13: "BodyType",
        0x14: "DevicePassword",
        0x15: "Password",
        0x16: "DeviceInformation",
        0x17: "Model",
        0x18: "IMEI",
        0x19: "FriendlyName",
        0x1a: "OS",
        0x1b: "OSLanguage",
        0x1c: "PhoneNumber",
        0x1d: "UserInformation",
        0x1e: "EmailAddresses",
        0x1f: "SmtpAddress",
        0x20: "UserAgent",
        0x21: "EnableOutboundSMS",
        0x22: "MobileOperator",
        0x23: "PrimarySmtpAddress",
        0x24: "Accounts",
        0x25: "Account",
        0x26: "AccountId",
        0x27: "AccountName",
        0x28: "UserDisplayName",
        0x29: "SendDisabled",
        0x2b: "RightsManagementInformation",
    },
    [WbxmlCodePage.ItemOperations]: {
        0x05: "ItemOperations",
        0x06: "Fetch",
        0x07: "Store",
        0x08: "Options",
        0x09: "Range",
        0x0a: "Total",
        0x0b: "Properties",
        0x0c: "Data",
        0x0d: "Status",
        0x0e: "Response",
        0x0f: "Version",
        0x10: "Schema",
        0x11: "Part",
        0x12: "EmptyFolderContents",
        0x13: "DeleteSubFolders",
        0x14: "UserName",
        0x15: "Password",
        0x16: "Move",
        0x17: "DstFldId",
        0x18: "ConversationId",
        0x19: "MoveAlways",
    },
    [WbxmlCodePage.ComposeMail]: {
        0x05: "SendMail",
        0x06: "SmartForward",
        0x07: "SmartReply",
        0x08: "SaveInSentItems",
        0x09: "ReplaceMime",
        0x0a: "Type", // not used
        0x0b: "Source",
        0x0c: "FolderId",
        0x0d: "ItemId",
        0x0e: "LongId",
        0x0f: "InstanceId",
        0x10: "MIME",
        0x11: "ClientId",
        0x12: "Status",
        0x13: "AccountId",
        0x15: "Forwardees",
        0x16: "Forwardee",
        0x17: "Name",
        0x18: "Email",
    },
    [WbxmlCodePage.Email2]: {
        0x05: "UmCallerID",
        0x06: "UmUserNotes",
        0x07: "UmAttDuration",
        0x08: "UmAttOrder",
        0x09: "ConversationId",
        0x0a: "ConversationIndex",
        0x0b: "LastVerbExecuted",
        0x0c: "LastVerbExecutionTime",
        0x0d: "ReceivedAsBcc",
        0x0e: "Sender",
        0x0f: "CalendarType",
        0x10: "IsLeapMonth",
        0x11: "AccountId",
        0x12: "FirstDayOfWeek",
        0x13: "MeetingMessageType",
        0x15: "IsDraft",
        0x16: "Bcc",
        0x17: "Send",
    },
};

const CODES_BY_PAGE: Readonly<Record<number, Readonly<Record<string, number>>>> = Object.fromEntries(
    Object.entries(TAGS_BY_PAGE).map(([page, tags]) => [
        Number(page),
        Object.fromEntries(Object.entries(tags).map(([code, name]) => [name, Number(code)])),
    ]),
);

/** Resolves a decoded tag byte's low 6 bits back into its tag name for the given code page. Falls back to a
 * synthetic `"Unknown0x.."` name (rather than throwing) for a page/code this table doesn't recognize - a
 * still-decodable, debuggable placeholder for a deferred code page or a future protocol version's new field,
 * rather than failing the entire document over one unrecognized tag. */
export function tagNameForCode(page: number, code: number): string {
    return TAGS_BY_PAGE[page]?.[code] ?? `Unknown0x${code.toString(16).padStart(2, "0")}`;
}

/** Resolves a tag name to its token byte (low 6 bits, before the content-flag bit is applied) for the given
 * code page. Unlike `tagNameForCode()`, this throws on an unknown pair - encoding a tag this table has no
 * token for is always a genuine programming error (an unregistered/deferred field), never legitimate input to
 * tolerate. */
export function codeForTagName(page: number, tag: string): number {
    const code = CODES_BY_PAGE[page]?.[tag];
    if (code === undefined) {
        throw new Error(`WbxmlCodePages: no token registered for tag "${tag}" on code page ${page}`);
    }
    return code;
}
